version: '3.8'

services:
  talt:
    build:
      context: .
      dockerfile: Dockerfile
    image: talt:latest
    container_name: talt-framework
    
    # GPU support
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_DEVICE=0
      - PYTHONHASHSEED=42
      - TOKENIZERS_PARALLELISM=false
    
    # Volume mounts
    volumes:
      - ./results:/app/results
      - ./data:/app/data
      - ./logs:/app/logs
      - ./checkpoints:/app/checkpoints
    
    # Working directory
    working_dir: /app
    
    # Keep container running
    stdin_open: true
    tty: true

  # CPU-only version
  talt-cpu:
    build:
      context: .
      dockerfile: Dockerfile
    image: talt:cpu
    container_name: talt-cpu
    environment:
      - CUDA_VISIBLE_DEVICES=""
      - PYTHONHASHSEED=42
    volumes:
      - ./results:/app/results
      - ./data:/app/data
      - ./logs:/app/logs
    profiles:
      - cpu
