version: '3.8'

services:
  talt:
    build:
      context: .
      dockerfile: Dockerfile
    image: talt:latest
    container_name: talt-framework
    
    # Modern GPU support (Docker Compose v2.3+)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    # Optimized settings for PyTorch performance
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 2gb
    
    # FIXED: Proper CUDA environment variables
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CUDA_DEVICE_ORDER=PCI_BUS_ID
      - PYTHONHASHSEED=42
      - TOKENIZERS_PARALLELISM=false
    
    # Volume mounts
    volumes:
      - ./results:/app/results
      - ./data:/app/data
      - ./logs:/app/logs
      - ./checkpoints:/app/checkpoints
    
    # Working directory
    working_dir: /app
    
    # Keep container running
    stdin_open: true
    tty: true

  